
// This file is usually auto-generated by Supabase CLI: supabase gen types typescript > path/to/database.types.ts
// For now, we'll define a basic structure. You should replace this with the auto-generated one.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      games: {
        Row: {
          id: string
          title: string
          description: string
          coverImage: string
          screenshots: string[]
          rvmGameId: string
          diskUrl: string
          emulatorCommand: string
          genre: string
          year: number
          developer: string
          publisher: string
          status: "finished" | "wip"
          created_at: string 
        }
        Insert: {
          id?: string // If auto-generated by DB or you provide it
          title: string
          description: string
          coverImage: string
          screenshots: string[]
          rvmGameId: string
          diskUrl: string
          emulatorCommand: string
          genre: string
          year: number
          developer: string
          publisher: string
          status: "finished" | "wip"
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          coverImage?: string
          screenshots?: string[]
          rvmGameId?: string
          diskUrl?: string
          emulatorCommand?: string
          genre?: string
          year?: number
          developer?: string
          publisher?: string
          status?: "finished" | "wip"
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Helper type for Game, assuming it mirrors the 'games' table Row
// This can be removed if Game type from data/games.ts is directly usable
// or if Supabase types are fully integrated.
export type GameRow = Database['public']['Tables']['games']['Row']
